devtool: Verify that stderr is not None type
The stderr is only valid in newer versions of bitbake since bitbake
commit 1ecc1d94 ("process: Do not mix stderr with stdout"), in older
versions of bitbake (e.g. oe-core/dunfell), the stderr is None type
and fails AUH updates as follows:

```
DEBUG:Running 'devtool  upgrade libfoo -S 1234abcd'
ERROR: libfoo: Failed(unknown error)
Traceback (most recent call last):
  File "/oe/auto-upgrade-helper/upgrade-helper.py", line 481, in run
    step(self.devtool, self.bb, self.git, self.opts, pkg_ctx)
  File "/oe/auto-upgrade-helper/modules/steps.py", line 85, in devtool_upgrade
    devtool_output = devtool.upgrade(pkg_ctx['PN'], pkg_ctx['NPV'], pkg_ctx['NSRCREV'])
  File "/oe/auto-upgrade-helper/modules/utils/devtool.py", line 30, in upgrade
    return self._cmd(cmd)
  File "/oe/auto-upgrade-helper/modules/utils/devtool.py", line 22, in _cmd
    return stdout + stderr
TypeError: can only concatenate str (not "NoneType") to str
INFO: libfoo: Auto commit changes ...
```

Check whether stderr is None and if it is, only use stderr.

Signed-off-by: Marek Vasut <marex@denx.de>